unique_ids:
  assets:
    standard-page.html: 5WGR2SESCYK3UVQCXHYPPP7BEMABK3OE
    theme.css: EEQWDLQJWLKXFJAW475OE4WKA5SQWAO3
  forms:
    Form1: CYZ3J364YZGSMHHC43URCBCVSORKUT2G
  modules: {}
  scripts: {}
  server_modules: {}
